language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - 0.5
  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("PkgName",coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("PkgName")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("PkgName")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
