language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - 0.5
#  - nightly
matrix:
  allow_failures:
    julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ApproxBayes"); Pkg.test("ApproxBayes"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("ApproxBayes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'cd(Pkg.dir("AppoxBayes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
